---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: zabbix_agent-opensuse-leap
    image: opensuse:leap
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        zabbix_agent_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: opensuse-leap
verifier:
  name: goss
  lint:
    name: yamllint
