---
#
# Ansible managed
#
repository:
  description: Install and configure zabbix_agent on your system.
  homepage: https://robertdebock.nl/
  topics: zabbix, agent, ansible, molecule, tox, playbook, hacktoberfest
