---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - n=0 ; until [ "$n" = 3 ] ; do tox --parallel all && break ; n=$((n+1)) ; done

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "tZZQJPQYA8DKJxSVnM5GrqGsFFF7pfxsItaHIsX/xlNIf+Uw3AMJxIZ7Bz/HYkZcm46BzyBAXsmDMpFOPMhWgqGP94h62sDrMVoICT0gICrDrBBDW3r+N39W09lqYP1Fig99kjGuRqhFuay0OrKVYeRFwXZNQaBx38WN6UE7QuCScKdpK+VrYjMd1aCqoW/bqtojCYwoS8UyqKjUsdkmDVhi2/a+jYl8HUFLOSV2dpr74RkOq2P7gZEVGNDO5bI7Z2ybIMK2WrINHpBgixkgQzweHTkrO4kD7Rt7iXUj0y86W1H4F0fl04+LQcwoffTf3eMwaU5syOwtfWU9FpxCDEgiQ8FlbhiqdApnddvOd5h2TuUbMU3mbFhYS576GSNg67lcaDX4PwyjvqYZRNDpUWbMq/XfghixoqwvzHSGjTX6Xf/2A7AA3lhjYE/3P2UMLKuzv17fb34QKacXd/0Dmls8dF+L7I7/2DPzKIiY87SQOMXvPeKOeOsOaIrcZ21Q6yPU7+snbdsdQRI0xs9iUfftrwUsx3AmNqMQwn6AgFzH+y1TacO/2bV9ZYQi7tli+CvZsBGe/vsMxzEm/E0MBwNT+1u3Rq7rajk+QCxZg0GR29vmunA28KMfGoL127324V9DRosQB/5QIyv6pY8SZOGVZiAbkq1qHxdt7kC1Ynw="
  email: false
