---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "sdU1K8JSHdym796xrE+RXAI+Fri0E5H2kBgA+9oOxvRsRIJj+SsO3lVpa+hbVvjQO/Dgr3U0cLPJkYRIAZeaUMeRVotrIfj8L9ZrTU7Ql/J+peq9Usw5K+ALXQfZ8zWu694jzwSED2ybuj/fgZpE0lLDD5hz8OuX8AEIFbJMwJAXAUric+mVQs0Fczeef/c9IuVbTnGda8tThjX1U39A91tog2fGFO8vnIZ8JiCJo33e8IytbJpqRiHNQECCZyvMepnE+XZeFgXW5V27K0SWMC+9Fv5aA7v4TCgl3TgrK9cYq48cQDFWNjZ1i97WnUn/LABfi3T0HCVK1hA15UKgqQTUHJZnEJgLiikmLIAuBM1bTcF4RAj+Ahb8J/o06QJxDeA1xzScvCOEA7ZHCZ0an/hkDSy3uNVgLdz0cQlATq5VssdM0kSnNGmG7DNRMvIvuO0pOqJi/R1HQnu29TRnod50RE8MRz5t1/J0kCycNEMnIp0j3RZoMU6DrNI+VmOFeV40HBU9bs0NTGAmOD/cLh1en4URVPr9pscmYfx3IuYACUzfEcyI0GhlpA2FvvvQebuMxREyEv09RhNHgIEPIasBlK+e79uRUYe3EXp84ZsG4lK6iuEsijADHGRlErXV+uSt3JDoj73XOpeQmY0rDMJogvyxLuK2MM5ZDpyIGdU="
  email: false
