---
- name: test if zabbix_agent_server_address is set correctly
  assert:
    that:
      - zabbix_agent_server_address is defined
    quiet: yes

- name: test if zabbix_agent_listen_port is set correctly
  assert:
    that:
      - zabbix_agent_listen_port is defined
      - zabbix_agent_listen_port is number
      - zabbix_agent_listen_port | int > 0
      - zabbix_agent_listen_port | int < 65536
    quiet: yes

- name: test if zabbix_agent_server_active_address is set correctly
  assert:
    that:
      - zabbix_agent_server_active_address is defined
    quiet: yes

- name: test if zabbix_agent_source_ip is set correctly
  assert:
    that:
    quiet: yes
  when:
    - zabbix_agent_source_ip is defined

- name: test if zabbix_agent_hostname is set correctly
  assert:
    that:
      - zabbix_agent_hostname is defined
    quiet: yes

- name: test if zabbix_agent_hostmetadata is set correctly
  assert:
    that:
      - zabbix_agent_hostmetadata is defined
    quiet: yes

- name: test if zabbix_agent_timeout is set correctly
  assert:
    that:
      - zabbix_agent_timeout is defined
      - zabbix_agent_timeout is number
      - zabbix_agent_timeout | int >= 0
    quiet: yes

- name: test if zabbix_agent_allow_key is set correctly
  assert:
    that:
    quiet: yes
  when:
    - zabbix_agent_allow_key is defined

- name: test if zabbix_agent_logremotecommands is set correctly
  assert:
    that:
      - zabbix_agent_logremotecommands is defined
      - zabbix_agent_logremotecommands in [ "0", "1" ]
    quiet: yes
