---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: zabbix-agent-debian
    box: debian/stretch64
    # - name: zabbix-agent-fedora
    #   box: fedora/30-cloud-base
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  inventory:
    host_vars:
      zabbix_agent-fedora:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: vagrant
