---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if connection still works
      ansible.builtin.ping:

    - name: Check if port 10050 is open
      ansible.builtin.wait_for:
        port: 10050
